added git_readme
SRA-VJTI/Intro_to_CV pull request #10
Opened 2021-05-17 09:52 UTC by Spnetic-5

Please review!

2021-05-17 10:06 UTC, gautam-dev-maker commented
* Add ```Table Of Content``` , refer [this](https://github.com/SRA-VJTI/Wall-E_v2.2/blob/master/3_MPU/README.md) readme
* Also add the content for git commands for commit ,pull & push

2021-05-17 10:13 UTC, Spnetic-5 commented
Okay!

2021-05-17 10:14 UTC, Spnetic-5 commented
Okay!

2021-05-17 12:43 UTC, meshtag commented
Thanks @Spnetic-5 for your contribution!
Can you please add some [info](https://frontendmasters.com/courses/git-in-depth/working-area-staging-area-repository/#:~:text=The%20working%20area%20is%20where,occur%20for%20the%20next%20commit.) about working area, staging area and upstream repository before explaining/introducing "commits" to the reader.

2021-05-17 12:49 UTC, Spnetic-5 commented
@meshtag on it!

2021-05-19 18:37 UTC, SAtacker commented
@Spnetic-5 could you add pull vs fetch (a line at least).
A general suggestion to keep filenames/folder `lower-case` names.

2021-05-19 18:48 UTC, Spnetic-5 commented
Yes @SAtacker, @kkothari2001 is working on another readme called git_commands.md, `pull vs fetch` along will all other git commands will be covered there.

2021-05-21 08:30 UTC, Spnetic-5 commented
Kindly review `task.md` and give suggestions.

2021-05-21 08:46 UTC, gautam-dev-maker commented
# 2.git_workflow.md
* No image is visible, correct it

# 4.task.md

* Do not add process to do it, just add the task to do  , and provide reference to markdown file where they can see how to do it.

Change names of files to this format “2_git_workflow.md”, same goes for all other files

2021-05-24 09:27 UTC, Spnetic-5 commented
@gautam-dev-maker, @amanchhaparia, @meshtag

2021-05-24 10:27 UTC, SAtacker requested changes
I have left a few comments in the review.
Mostly the content seems enough.
However, I couldn't help but notice that you are always creating a repository online and then cloning and doing the operations. I think we all know that there is a better way to do this.

Lastly, there's no demo for `git-reset` , some examples showing how to fetch remote and test changes without actually creating crappy branches, etc. but that can be left for later.
Regards,
Shreyas

2021-05-24 10:27 UTC, SAtacker commented on git_github/1_git_intro .md
> +
Please fix the links i.e. keep them relative `src="./assets/1.png"`.

2021-05-24 10:27 UTC, SAtacker commented on git_github/1_git_intro .md
> +### Run the following command in Terminal or cmd, change `<username>` with your own username:
This is just cloning. Where's syncing?
Can we replace it all by just cloning?

2021-05-24 10:30 UTC, kkothari2001 commented
@SAtacker the word "DEMO", was put just to show that there will be a demo when I explain. Concepts in git reset are difficult to explain in pictures only.

2021-05-24 14:44 UTC, merged